version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/server.crt:/etc/nginx/server.crt
      - ./cert/server.key:/etc/nginx/server.key
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    platform: linux/x86_64
    entrypoint: bash
    tty: true
