---
version: '3.8'
services:
  prometheus:
    ports:
      - 9090:9090
    build:
      dockerfile: prom/Dockerfile
      context: .
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox.yaml:/etc/blackbox_exporter/config.yml

  otel-collector:
    image: otel/opentelemetry-collector:0.84.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./test.log:/test.log
    ports:
      - "4317:4317" # for grpc
      - "4318:4318" # for http
    depends_on:
      - prometheus
