receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://prometheus.io
            - https://prometheus.io
            - https://opentelemetry.io
            - https://qiita.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox_exporter:9115
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      paging:

exporters:
  jaeger:
    endpoint: jaeger:14250
  file/no_rotation:
    path: /test.log
  otlphttp:
    metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [prometheus, hostmetrics]
      processors: [batch]
      exporters: [file/no_rotation, otlphttp]

