receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

processors:
  #probabilistic_sampler:
  #  sampling_percentage: 100
  #  sampling_priority: priority
  batch:
  # send_batch_size: 10000
  #  timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
