receivers:
  hostmetrics:
    collection_interval: 1m
    initial_delay: 1s
    scrapers:
      memory:

exporters:
  file:
    path: /dev/stdout

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [file]
