receivers:
  otlp:
    protocols:
      grpc:

processors:
  attributes:
    actions:
      - key: collector
        value: otel-collector
        action: insert

  tail_sampling:
    decision_wait: 10s
    num_traces: 10
    policies:
      [
        {
          name: longer-than-500ms,
          type: latency,
          latency: { threshold_ms: 500 },
        },
        {
          type: string_attribute,
          string_attribute: {
            key: "http.url",
            values: ["https://www.google.co.jp"]
          }
        }
      ]

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes, tail_sampling]
      exporters: [otlp]
  telemetry:
    logs:
      level: "debug"
