---
version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268" # for exporter
      - "16686:16686" # for browser

  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # for grpc
      - "4318:4318" # for http
    depends_on:
      - jaeger

  go-auto:
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    ports:
      - "9000:9000" # for grpc
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_GO_AUTO_TARGET_EXE=/main
      - OTEL_SERVICE_NAME=main
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - ./main:/main 
      - /proc:/host/proc
