# otel-config.yaml
---
receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

processors:
  batch:
    timeout: 1m
  attributes:
    actions:
      - key: user
        action: upsert
        value: gurasan

exporters:
  otlp/mackerel:
    endpoint: otlp.mackerelio.com:4317
    compression: gzip
    headers:
      Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
    timeout: 10s 

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [attributes, batch]
      exporters: [otlp/mackerel]
