receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  file:
    path: /dev/stdout
    logLebel: debug

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: "0.0.0.0:1888"

service:
  extensions: [pprof]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
