receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  file:
    path: /dev/stdout

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
