receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  file:
    path: /dev/stdout

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: "0.0.0.0:1888"

service:
  extensions: [pprof]
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
